Remove unused leave_ctx from h2_beam_lock structure and adjust callers.
Not sure why but I'm seeing gcc 10 warnings on s390x (only) for this.

h2_bucket_beam.c: In function 'h2_beam_abort':
h2_bucket_beam.c:222:9: error: 'bl.leave_ctx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  222 |         pbl->leave(pbl->leave_ctx, pbl->mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
h2_bucket_beam.c:710:18: note: 'bl.leave_ctx' was declared here
  710 |     h2_beam_lock bl;
      |                  ^~
h2_bucket_beam.c: In function 'h2_beam_close':
h2_bucket_beam.c:222:9: error: 'bl.leave_ctx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  222 |         pbl->leave(pbl->leave_ctx, pbl->mutex);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~