Fix build on i386
Whilst building on FreeBSD 10.2 i386 I ran into an error
```
--- mod_http2_la-h2_push.lo ---
  CC       mod_http2_la-h2_push.lo
--- mod_http2_la-h2_push.lo ---
h2_push.c:797:32: error: format specifies type 'long' but the argument has type 'apr_uint64_t' (aka 'unsigned long long') [
-Werror,-Wformat]
                  pval, delta, flex_bits, encoder->fixed_bits, delta&encoder->fixed_mask);
                               ^~~~~~~~~
1 error generated.
*** [mod_http2_la-h2_push.lo] Error code 1
```

From mod_http2/h2_push.c
```
    apr_uint64_t delta, flex_bits;
...
ap_log_perror(APLOG_MARK, GCSLOG_LEVEL, 0, encoder->pool,
                  "h2_push_diary_enc: val=%"APR_UINT64_T_HEX_FMT", delta=%"
                  APR_UINT64_T_HEX_FMT" flex_bits=%ld, "
                  "fixed_bits=%d, fixed_val=%"APR_UINT64_T_HEX_FMT,
                  pval, delta, flex_bits, encoder->fixed_bits, delta&encoder->fixed_mask);
```
`flex_bits` is formatted with `%l` (long) not `%ll` (long long). Change fixes build problems on i386 and I saw no regressions in amd64.